### ISSUE TITLE
Is there external Documentation or a Case Study on this gem?

### ISSUE THREAD

**Issue by lucasklaassen** [Shopify/response_bank#45]
Hey this gem looks very useful. I've been googling around and trying to find an article on this gem of the ROI Shopify has seen by using it or any other company. So far I've been unsuccessful.

Does anyone know of any external documentation for case study's for this gem?

I see a similar question was asked back in 2013 but the link doesn't exist anymore: https://github.com/Shopify/response_bank/issues/8

**Comment by rafaelfranca** [comment]
updated url: https://youtu.be/xh4GPjCmmbY?t=999
